### ISSUE TITLE
npm install caffeine-script error

### ISSUE THREAD

**Issue by jasonthane** [shanebdavis/caffeine-script#14]
x001:playground jason$ npm install caffeine-script
(node:26778) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "caffeine-script"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/art-object-tree-factory
npm ERR! 404 
npm ERR! 404  'art-object-tree-factory' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'caffeine-script'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jason/proj/playground/npm-debug.log

[npm-debug.log.zip](https://github.com/shanebdavis/caffeine-script/files/852649/npm-debug.log.zip)

**Comment by shanebdavis** [comment]
'art-object-tree-factory' is an npm now
