### ISSUE TITLE
npm install failure from within caffeine-script

### ISSUE THREAD

**Issue by jasonthane** [shanebdavis/caffeine-script#15]
x001:playground jason$ cd ../caffeine-script/
x001:caffeine-script jason$ ls
README.md		caffeine-mc.config.caf	examples		package.json		webpack.config.js
art.build.config.coffee	demo.caf		index.coffee		perf
build			demo2.caf		index.js		source
cafInCaf		editors			npm-debug.log		test
x001:caffeine-script jason$ npm install
(node:26802) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/art-object-tree-factory
npm ERR! 404 
npm ERR! 404  'art-object-tree-factory' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'caffeine-script'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jason/proj/caffeine-script/npm-debug.log
[npm-debug.log.zip](https://github.com/shanebdavis/caffeine-script/files/852653/npm-debug.log.zip)

**Comment by shanebdavis** [comment]
Just updated a bunch. "npm install caffeine-script" from scratch works. You can:

```
cd node_module/caffeine-script
npm test
```

Note: CaffeineScript v0.32.5 has 3 known-failing tests. The rest are all passing.
