### ISSUE TITLE
Tabs versus doublespaces

### ISSUE THREAD

**Issue by jasonthane** [shanebdavis/caffeine-script#17]
I tried to use Implicit Block Function Invocation as discussed in the [wiki here](https://github.com/shanebdavis/caffeine-script/wiki/Function-Invocation), and it didn't work the way I expected. The wiki says:

> Any value (a) followed by a block is invokes (a) as a function. Each statement in the block is an argument to that function.

My code:

~~~~
console.log
	Math.round
		123.456
~~~~

The results:

~~~~
--------------- jason@x001 Mon Apr 10 20:47:57 ---------------
69 ~/proj/caffeine-script-notes :) caf play.caf
CaffeineScriptParser only parsed: 46 of 69 characters

Parsing error at /Users/jason/proj/caffeine-script-notes/play.caf:6:1

Source:
...

console.log(hello)

console.log
<HERE>	Math.round
		123.456
...

expecting:
  statementWithoutEnd: toContinue: "root", startedAt: "1:1"
  importStatement:     toContinue: "root", startedAt: "1:1"

rules:
  statementWithoutEnd: "implicitArrayOrExpression tailControlOperatorComplexExpression+"
  importStatement:     "/import/ _ valueList end root"
~~~~

**Comment by jasonthane** [comment]
I just realized that this is because I was using tabs for my indentation instead of two spaces. It works the way it's documented using two spaces.

However, I will take the opportunity to open the conversation about the best way to educate the user to use spaces instead of tabs, if it is necessary to do so. Python currently strongly prefers the use of spaces over tabs, but it is not fatal not to use tabs.

Should CafScript allow tabs? If so, there may be future formatting battles. If not, and I might suggest not, can we create an informative error message for those like me who will be unaware, or who forget the convention?

**Comment by shanebdavis** [comment]
I've been anti-tab for a long time. Mixing tabs and spaces is the real
problem. I guess I'm biased by my own personal experience that files with
tabs end up with space indents too and then everything gets ugly. The best
solution I've found is to just always use spaces. I wish editors would
enforce files were either all tab-indented or all space-indented.

That would be one option for Caf - allow either, but o my if it's all one
or the either.

Either way, we could have much better parse errors.

**Comment by jasonthane** [comment]
I meant to say that the Python community strongly encourages and prefers spaces, not tabs, and I agree with your sentiments. 

I think my personal trouble is that in Xcode, I am used to hitting the tab key. However, as I'm just surprised to discover, in Xcode the tab key inserts four spaces. So it seems like there's a consensus against tabs.

Yes, we need a parse error that clearly informs the user that tabs are disallowed. Without this, a user might conclude that the language is broken. And it would be really great if your syntax highlighting extensions could configure Sublime and other editors to insert spaces when you hit the tab key, not sure if this is possible.

**Comment by shanebdavis** [comment]
Improved in 0.39.0. All-tabs or All-spaces allowed; mixed mode is rejected with a clear error.
