### ISSUE TITLE
Tabs not allowed for one-liner formatting

### ISSUE THREAD

**Issue by jasonthane** [shanebdavis/caffeine-script#19]
Just a note that tabs used for formatting in single lines are rejected with a non user-friendly error message.

Ex:

~~~
each co in companies       do console.log co['company name']
~~~

.. where the blank is a tab rather than multiple spaces results in an error

~~~
8 ~/proj/cas-corporate-metadata :) caf index.caf
error compiling: /Users/jason/proj/cas-corporate-metadata/index.caf
CaffeineScriptParser only parsed: 152 of 206 characters

Parsing error at /Users/jason/proj/cas-corporate-metadata/index.caf:7:21

Source:
...
workbook = xlsx.readFile('170228 DM Company List.xlsx')

companies = xlsx.utils.sheet_to_json workbook.Sheets['PCR Company Data']

each co in companies<HERE>	do console.log co['company name']
...

expecting:
  "/\\ *, *\\n*/": to-continue: "implicitArray", started-at: "7:1"
  end:             to-continue: "statement",     started-at: "7:1"
~~~

I may have an unhealthy obsession with using tabs inline, but others may as well, just thought you may want to consider some level of support, or at least a friendlier error message.

**Comment by shanebdavis** [comment]
Fix: all tabs are now replaced with spaces (one for one) before compiling (v0.43.0)
However, I strongly recommend using "tabs-as-spaces" and not actual tab-characters. Your CaffeineScript code will work just fine, but tabs are presented differently across editors and in the console. For consistency, use spaces :).
