### ISSUE TITLE
Function invocation must follow function declaration

### ISSUE THREAD

**Issue by jasonthane** [shanebdavis/caffeine-script#20]
It's bothersome to have to declare a function earlier in a file than you can invoke it (not exclusive to Caffeine-Script). Not an issue if you are declaring objects, but when scripting it's nice to be able to put convenience functions at the bottom.

Helps with readability when the reader wants to know what the script does without having to read all the convenience functions first.

Ex:

~~~
import &xlsx, &util




workbook = xlsx.readFile('170228 DM Company List.xlsx')

companies = xlsx.utils.sheet_to_json workbook.Sheets['PCR Company Data']

each co in companies 
  co.about = get_naics co['company name']






get_naics = (name) ->
  console.log name
~~~

produces an error:

16 ~/proj/cas-corporate-metadata :) caf index.caf
TypeError: get_naics is not a function
    at Caf.each (<anonymous>:2:372)
    at Object.each (./node_modules/caffeine-script-runtime/build/index.js:245:11)
    at Caf.defMod (<anonymous>:2:316)
    at Object.defMod (./node_modules/caffeine-script-runtime/build/index.js:593:32)
    at eval (<anonymous>:2:5)
    at ./node_modules/caffeine-mc/build/caf-command.js:1524:14

**Comment by shanebdavis** [comment]
That is intrinsic to JavaScript. However, if you can bundle it up in a
class and use static/class functions, then you can list them in any order.
I, too, put my helper functions at the end of my class listings for exactly
the same reasons.

This solution is only a few more tokens and it gets you what you are asking
for:

class Foo
@start: ->
..
@myHelper()

@myHelper: -> ...

.start() # dot-line-start-notation FTW!
