### ISSUE TITLE
Can I attach my .caf files in <script> tag ?

### ISSUE THREAD

**Issue by vlad0337187** [shanebdavis/caffeine-script#22]
Hello.

Can I attach my .caf files just like I did in CoffeeScript:

- add coffeescript compiler with tag: `<script type="text/javascript" src="./coffeescript_compiler.js"></script>`
- than just add all my CaffeineScript files with similar tags: `<script type="text/caffeinescript" src="./move_background.caf"></script>`

(because all my .coffee files during development are attached so, I don't want to use node or npm at all)

Thank you.

Best regards,
Vladislav

**Comment by shanebdavis** [comment]
Sorry to say I haven't built that part yet. I use webpack-dev-server for client-side development - and webpack to build my finally deployed .js.

**Comment by vlad0337187** [comment]
Understood.
Maybe I could use it one time =)
Thank you.

**Comment by vlad0337187** [comment]
I wanted to ask, are there any plans on future to make compilation of .caf inside of browser ?)
Thanks =)

**Comment by shanebdavis** [comment]
I don't think it would be that hard to make happen, but I don't currently have plans to implement it. I'm all for it; it's just a question of priorities. Webpack works for 100% of my needs right now, so I'm focused on enhancing the language. However, with your request, I'll keep a lookout for an opportunity to make it happen. 99% of the compiler is browser friendly already.

**Comment by vlad0337187** [comment]
@shanebdavis , Well, thank you. 

I installed node too, but compile scripts not using webpack, but using caf + own script like:

```
import os
... ... ...
path_to_compiler = f"{current_dir}/node_modules/caffeine-mc/caf"
os.system(f'{path_to_compiler} {flags} {input_file} {output_file})
```

**Comment by vlad0337187** [comment]
Also have bound to topic question:
I have such source file:
test.caffeine:
```
a = 4
```

I get such result file:
```
"use strict";
let Caf = require("caffeine-script-runtime");
Caf.defMod(module, () => {
  let a;
  return a = require("./static/gatekeeper/caffeine/login_page.caffeine");
});
```

With webpack all works great, but if not to use it - I need some implementation of require function (like commonjs).

Can it be compiled direct to js code (not to depend on require, maybe, to use imports or some other implementation)?

For output to be like this:
```
  let a;
  return a = require("./static/gatekeeper/caffeine/login_page.caffeine");
```
