### ISSUE TITLE
Question: Block string syntax

### ISSUE THREAD

**Issue by vlad0337187** [shanebdavis/caffeine-script#23]
Hello.

Is it normal, that such syntax is valid:
```
console.log "' function launched"
console.log 'function launched'

console.log "" function launched
```

, but such - not:
```
console.log '' function launched
```

Thanks.
Best regards,
Vladislav.

**Comment by shanebdavis** [comment]
Good question. That is normal. ‘’ (two single quotes) does not support
block-strings. The reason is sometimes you want an unambiguous empty string.

**Comment by vlad0337187** [comment]
@shanebdavis , thank you very much.
Yeah, you're right, it's a good choise.

I'll close this issue then.
